# Generated by Django 4.2.30 on 2026-05-01 01:04

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FareRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=20, unique=True)),
                ('base_fare_tzs', models.DecimalField(decimal_places=2, help_text='Flat starting fare (TZS)', max_digits=10)),
                ('per_km_rate_tzs', models.DecimalField(decimal_places=2, help_text='Fare per kilometer (TZS)', max_digits=8)),
                ('per_minute_rate_tzs', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=8)),
                ('minimum_fare_tzs', models.DecimalField(decimal_places=2, default=Decimal('1500.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurgeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('center_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('center_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('radius_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('is_active', models.BooleanField(default=False)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_riders', 'No Riders Available')], db_index=True, default='pending', max_length=20)),
                ('vehicle_type', models.CharField(choices=[('economy', 'Economy Boda'), ('deluxe', 'Deluxe Boda'), ('express', 'Express Boda')], default='economy', max_length=20)),
                ('pickup_address', models.CharField(max_length=512)),
                ('pickup_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('pickup_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('destination_address', models.CharField(max_length=512)),
                ('destination_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('destination_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('route_polyline', models.TextField(blank=True, help_text='Encoded Mapbox route geometry', null=True)),
                ('estimated_distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('estimated_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('base_fare', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('distance_fare', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('surge_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('total_fare', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('actual_distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('actual_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('final_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ride_requests', to=settings.AUTH_USER_MODEL)),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_rides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ride Request',
                'verbose_name_plural': 'Ride Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='RideRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
                ('rated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='rides.riderequest')),
            ],
        ),
    ]
