# Generated by Django 4.2.30 on 2026-05-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='midway_stops',
            field=models.JSONField(blank=True, help_text='List of intermediate stops [{address, lat, lng}]', null=True),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='vehicle_type',
            field=models.CharField(choices=[('ride', 'Boda Ride'), ('delivery', 'Boda Delivery')], default='ride', max_length=20),
        ),
    ]
