# Generated by Django 4.2.30 on 2026-05-13 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodaboda_auth', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='guarantor_id_back',
            field=models.FileField(blank=True, null=True, upload_to='kyc/guarantor/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='guarantor_id_front',
            field=models.FileField(blank=True, null=True, upload_to='kyc/guarantor/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='guarantor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='guarantor_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='local_authority_letter',
            field=models.FileField(blank=True, null=True, upload_to='kyc/authority_letters/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nida_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
