# Generated by Django 4.2.30 on 2026-05-01 01:04

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(help_text='e.g. Honda, TVS', max_length=100)),
                ('model_name', models.CharField(help_text='e.g. Boxer BM 150, HLX', max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('plate_number', models.CharField(max_length=50, unique=True)),
                ('chassis_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active & Deployed'), ('maintenance', 'Under Maintenance'), ('idle', 'Idle'), ('decommissioned', 'Decommissioned')], db_index=True, default='idle', max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric')], default='petrol', max_length=20)),
                ('fuel_tank_liters', models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=5)),
                ('fuel_efficiency_kpl', models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Average kilometers per liter of fuel', max_digits=5)),
                ('odometer_km', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('inspection_due_date', models.DateField(blank=True, null=True)),
                ('logbook', models.FileField(blank=True, null=True, upload_to='fleet/logbooks/')),
                ('insurance_doc', models.FileField(blank=True, null=True, upload_to='fleet/insurance/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_rider', models.OneToOneField(blank=True, limit_choices_to={'role': 'rider'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicle', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Fleet Vehicles',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('service', 'Routine Service'), ('repair', 'Repair'), ('tyre', 'Tyre Change'), ('oil_change', 'Oil Change'), ('inspection', 'Inspection'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('cost_tzs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('odometer_at_service_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('performed_by', models.CharField(blank=True, help_text='Garage or technician name', max_length=255, null=True)),
                ('performed_at', models.DateField()),
                ('next_service_due_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('next_service_due_date', models.DateField(blank=True, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='fleet/maintenance_receipts/')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel')], max_length=20)),
                ('price_per_liter_tzs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('region', models.CharField(default='Dar es Salaam', max_length=100)),
                ('effective_date', models.DateField(db_index=True)),
                ('source', models.CharField(blank=True, help_text='Source of price data', max_length=255, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fuel Price Record',
                'ordering': ['-effective_date'],
                'unique_together': {('fuel_type', 'effective_date', 'region')},
            },
        ),
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liters_added', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cost_per_liter_tzs', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_cost_tzs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('odometer_at_fill_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('station_name', models.CharField(blank=True, max_length=255, null=True)),
                ('refilled_at', models.DateTimeField()),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='fleet/fuel_receipts/')),
                ('rider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_logs', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='fleet.vehicle')),
            ],
        ),
    ]
