# Generated by Django 4.2.30 on 2026-05-13 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='commercial_registration_doc',
            field=models.FileField(blank=True, null=True, upload_to='fleet/commercial/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_capacity_cc',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_tbs_inspected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='local_authority_permits',
            field=models.FileField(blank=True, null=True, upload_to='fleet/permits/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='ownership_transfer_doc',
            field=models.FileField(blank=True, null=True, upload_to='fleet/ownership/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tin_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transport_group_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RiderContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_doc', models.FileField(upload_to='fleet/contracts/')),
                ('start_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_contracts', to=settings.AUTH_USER_MODEL)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_contracts', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='fleet.vehicle')),
            ],
        ),
    ]
