# Generated by Django 4.2.30 on 2026-05-13 19:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_vehicle_logbook_control_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridercontract',
            name='daily_rent_tzs',
            field=models.DecimalField(decimal_places=2, default=Decimal('25000.00'), max_digits=12),
        ),
    ]
