# Generated by Django 4.2.30 on 2026-05-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_vehicle_commercial_registration_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='insurance_sticker_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='latra_license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='logbook_control_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
