# Generated by Django 4.2.30 on 2026-05-13 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodaboda_auth', '0004_customuser_guarantor_id_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_password_reset_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
