# Generated by Django 4.2.30 on 2026-05-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodaboda_auth', '0005_customuser_is_suspended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='daily_target_tzs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Passenger'), ('rider', 'Rider (Independent)'), ('employed_rider', 'Rider (Employed by Owner)'), ('owner', 'Fleet Owner'), ('admin', 'Super Admin')], default='client', max_length=20),
        ),
    ]
