# Generated by Django 4.2.30 on 2026-05-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_riderequest_midway_stops'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farerule',
            old_name='vehicle_type',
            new_name='ride_type',
        ),
        migrations.RenameField(
            model_name='riderequest',
            old_name='vehicle_type',
            new_name='ride_type',
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='ride_type',
            field=models.CharField(choices=[('ride', 'Boda Ride'), ('delivery', 'Boda Delivery')], default='ride', max_length=20),
        ),
    ]
