# Generated by Django 4.2.30 on 2026-05-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_rename_vehicle_type_riderequest_ride_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='rider_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='rider_lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='rider_location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
