# Generated by Django 4.2.30 on 2026-05-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_riderequest_rider_lat_riderequest_rider_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted (Rider)'), ('confirmed', 'Confirmed (Client)'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_riders', 'No Riders Available')], db_index=True, default='pending', max_length=20),
        ),
    ]
