# Generated by Django 4.2.30 on 2026-05-13 19:42

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet', '0004_ridercontract_daily_rent_tzs'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='total_debt_tzs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount rider owes the owner', max_digits=14),
        ),
        migrations.CreateModel(
            name='FleetExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('fuel', 'Fuel'), ('maintenance', 'Maintenance'), ('repair', 'Repair'), ('fine', 'Traffic Fine'), ('permit', 'Permit/License'), ('other', 'Other')], max_length=20)),
                ('amount_tzs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('expense_date', models.DateField()),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='fleet/expenses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_tzs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_amount_tzs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('submission_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Mobile money transaction ID or receipt number', max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_submissions', to=settings.AUTH_USER_MODEL)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submission_date', '-created_at'],
                'unique_together': {('rider', 'submission_date')},
            },
        ),
    ]
