# Generated by Django 4.2.30 on 2026-05-13 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_wallet_total_debt_tzs_fleetexpense_dailysubmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fleetexpense',
            old_name='owner',
            new_name='user',
        ),
    ]
