# Generated by Django 4.2.30 on 2026-05-01 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('zone_type', models.CharField(choices=[('service_area', 'Service Area'), ('no_go', 'No-Go Zone'), ('hotspot', 'Pickup Hotspot'), ('surge', 'Surge Pricing Zone')], max_length=20)),
                ('boundary', models.JSONField(help_text='GeoJSON polygon coordinates')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MapRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_geometry', models.TextField(help_text='Mapbox encoded route geometry string')),
                ('distance_meters', models.IntegerField()),
                ('duration_seconds', models.IntegerField()),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='map_route', to='rides.riderequest')),
            ],
        ),
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('heading', models.FloatField(default=0.0)),
                ('speed_kmh', models.FloatField(default=0.0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='rides.riderequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location Breadcrumb',
                'ordering': ['recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('heading', models.FloatField(default=0.0, help_text='Degrees from North (0-360)')),
                ('speed_kmh', models.FloatField(default=0.0)),
                ('accuracy_meters', models.FloatField(default=0.0)),
                ('is_online', models.BooleanField(db_index=True, default=False)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_location', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Location',
                'verbose_name_plural': 'Live Locations',
            },
        ),
    ]
